# a list of dictionarys
# key are the same
import random

question_set = [[{"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The Tiananmen Square protests of 1989 were held in Hong Kong.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The Spitfire originated from a racing plane.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The United States Department of Homeland Security was formed in response to the September 11th attacks.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The United States was a member of the League of Nations.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "United States President John F. Kennedy was assassinated during his presidential motorcade in Atlanta, Georgia on November 22nd, 1963.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "Former United States Presidents John Adams and Thomas Jefferson died within hours of each other.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "Kublai Khan is the grandchild of Genghis Khan?",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The French Kingdom helped the United States gain their independence over Great Britain during the Revolutionary War.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The United States of America was the first country to launch a man into space.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "Thomas Crapper was a plumber who invented the flushing toilet.",
                  "correct_answer": "False", "incorrect_answers": ["True"]}],
                [
                    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                     "question": "French is an official language in Canada.", "correct_answer": "True",
                     "incorrect_answers": ["False"]},
                    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                     "question": "Bulls are attracted to the color red.", "correct_answer": "False",
                     "incorrect_answers": ["True"]},
                    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                     "question": "The color orange is named after the fruit.", "correct_answer": "True",
                     "incorrect_answers": ["False"]},
                    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                     "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
                     "correct_answer": "True", "incorrect_answers": ["False"]},
                    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                     "question": "Adolf Hitler was born in Australia. ", "correct_answer": "False",
                     "incorrect_answers": ["True"]},
                    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                     "question": "When you cry in space, your tears stick to your face.", "correct_answer": "True",
                     "incorrect_answers": ["False"]},
                    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                     "question": "The Lego Group was founded in 1932.", "correct_answer": "True",
                     "incorrect_answers": ["False"]},
                    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                     "question": "One of Donald Trump&#039;s 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.",
                     "correct_answer": "True", "incorrect_answers": ["False"]},
                    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                     "question": "Jingle Bells was originally meant for Thanksgiving", "correct_answer": "True",
                     "incorrect_answers": ["False"]},
                    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                     "question": "Ping-Pong originated in England", "correct_answer": "True",
                     "incorrect_answers": ["False"]}]
                ]
question_data = random.choice(question_set)
